# GitHub Trending Repositories
schedule:
  cron: "0 10 * * *"  # Daily at 10 AM UTC
  timezone: "UTC"
  enabled: true

providers:
  - id: openrouter:minimax/minimax-m2:free
    config:
      temperature: 0.7
      max_tokens: 2000

memory:
  enabled: true
  updateStrategy: extract
  deduplicationPrompt: |
    Previous memory: {{memory}}
    Today: {{date}}

    Are there new trending repositories that differ significantly from yesterday?
    Reply with JSON: {"shouldRun": true/false, "reason": "explanation"}

  extractPrompt: |
    Extract recurring languages, frameworks, and project categories from trending repos.
    Note any emerging patterns in open source development.

outputs:
  - type: commit
    path: dashboard/data/tasks/github-trending.json
    message: "chore(github): update trending repositories [skip ci]"

  - type: file
    path: results/{{date}}.md
    format: markdown
